### ISSUE TITLE
2 Kings regex

### ISSUE THREAD

**Issue by tayknight** [jonathanvanschenck/biblescrapeway#1]
Too simple for a pull request :)

`["1[ _]?[Kk]","2 Kings", 25], `

should be

`["2[ _]?[Kk]","2 Kings", 25],`

**Comment by jonathanvanschenck** [comment]
Good catch! Thanks for the PR 👍

**Comment by jonathanvanschenck** [comment]
Thanks! I'll check this out and #2 to see if I can merge in a fix soon

**Comment by jonathanvanschenck** [comment]
Fixed with [this commit](https://github.com/jonathanvanschenck/biblescrapeway/commit/1fc601e2434dc20aa0aca32c575ee755db591785https://github.com/jonathanvanschenck/biblescrapeway/commit/1fc601e2434dc20aa0aca32c575ee755db591785)https://github.com/jonathanvanschenck/biblescrapeway/commit/1fc601e2434dc20aa0aca32c575ee755db591785, and version 0.1.6
